### ISSUE TITLE
ms error

### ISSUE THREAD

**Issue by MetalOoze05** [Androz2091/discord-giveaways#121]
Hey there,
I tried using the package but it is giving me an error in the ms part which dosent go forward and console logs the error given below:
```(node:2548) UnhandledPromiseRejectionWarning: Error: val is not a non-empty string or a valid number. val={"channelID":"752058253424197692","deleted":false,"id":"777903503569453056","type":"DEFAULT","system":false,"content":"15s","authorID":"331005037062914050","pinned":false,"tts":false,"nonce":"777902531987636224","embeds":[],"attachments":[],"createdTimestamp":1605537047999,"editedTimestamp":0,"webhookID":null,"applicationID":null,"activity":null,"flags":0,"reference":null,"guildID":"752049360325574687","cleanContent":"15s"}
    at module.exports (C:\Users\Ayan\Desktop\Ayan Folders\Zhane-bot\node_modules\ms\index.js:34:9)
    at C:\Users\Ayan\Desktop\Ayan Folders\Zhane-bot\commands\giveaways\g-create.js:33:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The part where I define ms and work on the stuffs is given below:
```
message.channel.send(gEmbed.setDescription(`Nice.... now provide the giveaway duration` + "\n" + "Format: `d`, `h`, `m`, `s`"))
                message.channel.awaitMessages(m => m.author.id == message.author.id, {max: 1, time:30000}).then(collected => {
                    const duration = collected.first()
                    if (isNaN(ms(duration))) {
                        return message.channel.send(`**${errorEmoji} | Operation cancelled as you did not provide a valid time!**`)
                    }
```

**Comment by NicoHd105** [comment]
Could you please provide the full error... We cannot help you if we don't have a error message, you only provided the path of the error.

**Comment by MetalOoze05** [comment]
Nevermind as that issue got fixed when I used ``ms(`${duration})``
