### ISSUE TITLE
Cannot read property 'giveaways' of undefined

### ISSUE THREAD

**Issue by Dragonizedpizza** [Androz2091/discord-giveaways#167]
```Cannot read property 'giveaways' of undefined
{
  "stack": "TypeError: Cannot read property 'giveaways' of undefined
    at GcreateCommand.run (/home/container/src/commands/misc/gcreate.js:25:41)
    at module.exports (/home/container/src/events/message.js:52:24)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)"
}

**Comment by Nico105** [comment]
gcreate.js line 25, send it

**Comment by Dragonizedpizza** [comment]
hi @Nico105, I fixed that error but now get this.
```Cannot read property 'start' of undefined
{
  "stack": "TypeError: Cannot read property 'start' of undefined
    at GcreateCommand.run (/home/container/src/commands/misc/gcreate.js:39:37)
    at module.exports (/home/container/src/events/message.js:52:24)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)"
}

**Comment by Dragonizedpizza** [comment]
Code: ```





const giveaways = require('discord-giveaways');
const Command = require("../Command.js");
const ms = require("ms");
const num = require("num-parse");
const { GiveawayManager } = require('discord-giveaways');

module.exports = class GcreateCommand extends Command {
  constructor(client) {
    super(client, {
      name: 'gcreate',
      aliases: ['gstart'],
      usage: 'gcreate <time> <winners> <prize>',
      description: 'Starts a giveaway.',
      type: client.types.MISC,
      clientPermissions: ['SEND_MESSAGES', 'EMBED_LINKS', 'MANAGE_ROLES'],
      userPermissions: ['MANAGE_ROLES'],
      examples: ['gcreate 1d 1w Discord Nitro!']
    });
  }

    async run(message, args, Discord) {
        if (!message.member.hasPermission("MANAGE_GUILD") && !message.member.roles.cache.some(r => r.name.toLowerCase() === "giveaway")) return message.channel.send("❌ | You don't have `MANAGE_GUILD` permission or `Giveaway` role to create giveaways!");
        let time = args[0];
        if (!time) return message.channel.send("❌ | Please provide valid time. Eg: `1h`, `1d` etc.");
        if (ms(time) > ms("10d")) {
            return message.channel.send("❌ | Giveaway duration should be less than 10d.");
        }
        let winners = args[1];
        if (!winners) return message.channel.send("❌ | Please provide valid winner count. Eg: `1w`, `2w`");
        winners = num(winners, 1);
        if (winners > 15) return message.channel.send("❌ | Giveaway winners should be less than 15.");
        let prize = args.slice(2).join(" ");
        if (!prize) return message.channel.send("❌ | Please provide the prize for giveaway. Eg: `d!create 1d 2w Discord Nitro`");

        this.client.GiveawayManager.start(message.channel, {
            time: ms(time),
            winnerCount: winners,
            prize: prize,
            hostedBy: message.author,
            messages: {
                giveaway: "🎉 **Giveaway** 🎉",
                giveawayEnded: "🎊 **Giveaway Ended!** 🎊",
                timeRemaining: "Time left: **{duration}**!",
                inviteToParticipate: "React with \"🎉\" to participate!",
                winMessage: "🎊 Congrats, {winners} for winning **{prize}**!",
                embedFooter: `${this.client.user.tag}`,
                noWinner: "Nobody won because of the invalid participations!",
                hostedBy: "Hosted by: {user}",
                winners: "winner(s)",
                endedAt: "Ended at",
                units: {
                    seconds: "seconds",
                    minutes: "minutes",
                    hours: "hours",
                    days: "days"
                }
            }
        });
        if (message.deletable) message.delete();
        return;
    }
}

**Comment by Dragonizedpizza** [comment]
Oop GitHub code block breks

**Comment by Nico105** [comment]
```js
// Requires Manager from discord-giveaways
const { GiveawaysManager } = require('discord-giveaways');
// Starts updating currents giveaways
const manager = new GiveawaysManager(client, {
    storage: './giveaways.json',
    updateCountdownEvery: 10000,
    hasGuildMembersIntent: false,
    default: {
        botsCanWin: false,
        exemptPermissions: ['MANAGE_MESSAGES', 'ADMINISTRATOR'],
        embedColor: '#FF0000',
        reaction: '🎉'
    }
});
// We now have a giveawaysManager property to access the manager everywhere!
client.giveawaysManager = manager;
```
Ahm you have to intialize the manager first before using it...
You do not have to require the module in your command file, just add the code i provided to your index or bot.js
And I would suggets you look through the README

**Comment by Dragonizedpizza** [comment]
```emitter.on is not a function
{
  "stack": "TypeError: emitter.on is not a function
    at Function.on (events.js:733:11)
    at GiveawaysManager._init (/home/container/node_modules/discord-giveaways/src/Manager.js:464:21)"
}

**Comment by Dragonizedpizza** [comment]
@Nico105 Whattt

**Comment by Dragonizedpizza** [comment]
```Cannot read property 'start' of undefined
{
  "stack": "TypeError: Cannot read property 'start' of undefined
    at GcreateCommand.run (/home/container/src/commands/misc/gcreate.js:34:37)
    at module.exports (/home/container/src/events/message.js:52:24)
    at Client.emit (events.js:314:20)
    at MessageCreateAction.handle (/home/container/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/container/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/home/container/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/home/container/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)"
}```
@Nico105 this as well

**Comment by Nico105** [comment]
You have to add the manager "creation" and pass your client so `this.client` in your case i guess.
IF you have done that then your `.start` error is because you wrote `GiveawayManager` and not `giveawaysManager`
Have a look at the example bot which is linked in the README file if you don't understand what I want to say and I hope you can understand then

**Comment by Dragonizedpizza** [comment]
How do I do that-

**Comment by Nico105** [comment]
https://github.com/Androz2091/giveaways-bot
Just look at the index.js  file that is the same thing i sent, you just have to add it
Then look at the command files, there is no need to do `require('discord-giveaways')` in them you will see.

**Comment by Nico105** [comment]
Have you understood what was/is wrong?

**Comment by Dragonizedpizza** [comment]
No.

**Comment by Nico105** [comment]
![image](https://user-images.githubusercontent.com/63612668/104044366-853e3180-51dd-11eb-9df9-e58b46324884.png)
Just put the manager code in your index or bot .js, nothing more

**Comment by Dragonizedpizza** [comment]
tysm @Nico105, I found the error.
`GiveawayManager` instead of `giveawaysManager`.
