### ISSUE TITLE
Node Module Error

### ISSUE THREAD

**Issue by dylanjamesdev** [Androz2091/discord-giveaways#183]
```
0|bot      | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
0|bot      | TypeError: Cannot read property 'id' of undefined
0|bot      |     at Giveaway.checkWinnerEntry (/root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:302:42)
0|bot      |     at Giveaway.roll (/root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:333:45)
0|bot      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|bot      |     at async /root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:400:29
0|bot      | [Unhandled Rejection] TypeError: Cannot read property 'id' of undefined
0|bot      |     at Giveaway.checkWinnerEntry (/root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:302:42)
0|bot      |     at Giveaway.roll (/root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:333:45)
0|bot      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|bot      |     at async /root/tritan-bot/node_modules/discord-giveaways/src/Giveaway.js:400:29```

It doesn't seem to effect anything, and I have updated to the latest version. Best :)

**Comment by Androz2091** [comment]
Hello @dylanjamesdev, are you using the latest version?

**Comment by dylanjamesdev** [comment]
I thought I was but for some reason the package would update time after time to the same version. I removed all node modules and reinstalled and the error has gone away.
