### ISSUE TITLE
Giveaway end error, roll function

### ISSUE THREAD

**Issue by MaximKing1** [Androz2091/discord-giveaways#207]
```js
Strider-Testing | TypeError: Cannot read property 'id' of undefined
Strider-Testing |     at Giveaway.checkWinnerEntry (/usr/src/Sharding-Test/node_modules/discord-giveaways/src/Giveaway.js:302:42)
Strider-Testing |     at Giveaway.roll (/usr/src/Sharding-Test/node_modules/discord-giveaways/src/Giveaway.js:333:45)
Strider-Testing |     at runMicrotasks (<anonymous>)
Strider-Testing |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
i get this when using sharding, when i started a giveaway it ended but the message was stuck at 5 Seconds but clicking on it registered the giveaway already ended event i setup on the manager... im using the Sharding thing in the manager function also using the Custom Embed and DB ....

**Comment by MaximKing1** [comment]
```
db.once("ready", async () => {
        if ((await db.get("giveaways")) === null) await db.set("giveaways", []);
      });
    
      const { GiveawaysManager } = require("discord-giveaways");
      class GiveawayManagerWithOwnDatabase extends GiveawaysManager { 
       async refreshStorage() {
        // This should make all shard refreshing their cache with the updated database
        return client.shard.broadcastEval(() => this.giveawaysManager.getAllGiveaways());
       }
        async getAllGiveaways() {
            return await db.get("giveaways");
        }
        async saveGiveaway(messageID, giveawayData) {
            await db.push("giveaways", giveawayData);
            return true;
        }
        async editGiveaway(messageID, giveawayData) {
            const giveaways = await db.get("giveaways");
            const newGiveawaysArray = giveaways.filter((giveaway) => giveaway.messageID !== messageID);
            newGiveawaysArray.push(giveawayData);
            await db.set("giveaways", newGiveawaysArray);
            return true;
        }
        async deleteGiveaway(messageID) {
            const data = await db.get("giveaways");
            const newGiveawaysArray = data.filter((giveaway) => giveaway.messageID !== messageID);
            await db.set("giveaways", newGiveawaysArray);
            return true;
        }
      };

    const manager = new GiveawayManagerWithOwnDatabase(client, {
        storage: false,
        updateCountdownEvery: 10000,
        hasGuildMembersIntent: true,
        default: {
          botsCanWin: false,
          embedColor: "#002df7",
          embedColorEnd: "#FF0000",
          exemptPermissions: [ 'ADMINISTRATOR' ],
          reaction: '🎉'
    }});
    client.giveawaysManager = manager;
```
thats the giveaway manager sharding, does it need to be in the sharding file?

**Comment by Nico105** [comment]
#203 has the error fix, it is NOT because of sharding

**Comment by MaximKing1** [comment]
Oh alright thank you that’s good to know it’s not my config xD tbh I started doing Sharding today and that was the only issue so POGGERS are working!

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
