### ISSUE TITLE
guild.member is not a function

### ISSUE THREAD

**Issue by jameslinimk** [Androz2091/discord-giveaways#217]
```js
TypeError: guild.member is not a function
    at Giveaway.checkWinnerEntry (/pro/burito/node_modules/discord-giveaways/src/Giveaway.js:311:30)
    at Giveaway.roll (/pro/burito/node_modules/discord-giveaways/src/Giveaway.js:343:95)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /pro/burito/node_modules/discord-giveaways/src/Giveaway.js:407:29
Promise {
  <rejected> TypeError: guild.member is not a function
      at Giveaway.checkWinnerEntry (/pro/burito/node_modules/discord-giveaways/src/Giveaway.js:311:30)
      at Giveaway.roll (/pro/burito/node_modules/discord-giveaways/src/Giveaway.js:343:95)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /pro/burito/node_modules/discord-giveaways/src/Giveaway.js:407:29
}
```
Whenever a giveaway ends, or the bot starts

**Comment by Nico105** [comment]
You have installed the `develop` branch right?
I will look into it, it's just a dev branch after all.

**Comment by Nico105** [comment]
Does this happen for a test bot = single guild? 
Or is this in a production bot with lots of guilds?

**Comment by Nico105** [comment]
Do you have any special discord bot settings active?

**Comment by Nico105** [comment]
I got informed, this is because you're using the master or some else branch of `discord.js` where they removed the `member` getter, I will adjust it when I have time.

**Comment by Nico105** [comment]
🎉 v4.5.0 is now released!
