### ISSUE TITLE
MySql problem!

### ISSUE THREAD

**Issue by Chiquis2005** [Androz2091/discord-giveaways#231]
```

> Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x8E\x89\xF0\x9F...' for column `s864_admin`.`giveaways`.`data` at row 1
>     at Query.Sequence._packetToError (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)        
>     at Query.ErrorPacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
>     at Protocol._parsePacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:291:23)
>     at Parser._parsePacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Parser.js:433:10)
>     at Parser.write (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Parser.js:43:10)
>     at Protocol.write (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:38:16)
>     at Socket.<anonymous> (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:88:28)
>     at Socket.<anonymous> (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:526:10)
>     at Socket.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Socket.Readable.push (internal/streams/readable.js:223:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
>     --------------------
>     at Protocol._enqueue (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:144:48)
>     at Connection.query (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:198:25)
>     at C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\giveawayfunction.js:56:21
>     at new Promise (<anonymous>)
>     at GiveawayManagerWithOwnDatabase.saveGiveaway (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\giveawayfunction.js:55:20)
>     at C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\discord-giveaways\src\Manager.js:205:24
>     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
>   code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
>   errno: 1366,
>   sqlMessage: "Incorrect string value: '\\xF0\\x9F\\x8E\\x89\\xF0\\x9F...' for column `s864_admin`.`giveaways`.`data` at row 1",
>   sqlState: '22007',
>   index: 0,
>   sql: 'INSERT INTO `giveaways` (`message_id`, `data`) VALUES (\'817244813501399050\',\'{\\"messageID\\":\\"817244813501399050\\",\\"channelID\\":\\"758508173077512203\\",\\"guildID\\":\\"757778032088842291\\",\\"startAt\\":1614916747288,\\"endAt\\":1614916807288,\\"ended\\":false,\\"winnerCount\\":1,\\"winners\\":[],\\"prize\\":\\"xde\\",\\"messages\\":{\\"giveaway\\":\\"🎉🎉 **SORTEO** 🎉🎉\\",\\"giveawayEnded\\":\\"🎉🎉 **SORTEO TERMINADO** 🎉🎉\\",\\"inviteToParticipate\\":\\"Reacciona 🎉 para participar!\\",\\"timeRemaining\\":\\"Tiempo Restante: **{duration}**!\\",\\"winMessage\\":\\"Felicidades, {winners}! Acabas 
> de ganar **{prize}**!:partying_face::partying_face:\\\\n{messageURL}\\",\\"embedFooter\\":\\"Sorteo\\",\\"noWinner\\":\\"Sorteo Cancelado, No hay suficientes participantes.\\",\\"winners\\":\\"Ganador(es)\\",\\"endedAt\\":\\"Termina en\\",\\"hostedBy\\":\\"Hosteado por: {user}\\",\\"units\\":{\\"seconds\\":\\"segundos\\",\\"minutes\\":\\"minutos\\",\\"hours\\":\\"horas\\",\\"days\\":\\"dias\\",\\"pluralS\\":false}},\\"hostedBy\\":null,\\"winnerIDs\\":[]}\')'
> }
> (node:720) UnhandledPromiseRejectionWarning: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x8E\x89\xF0\x9F...' for column `s864_admin`.`giveaways`.`data` at row 1
>     at Query.Sequence._packetToError (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)        
>     at Query.ErrorPacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
>     at Protocol._parsePacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:291:23)
>     at Parser._parsePacket (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Parser.js:433:10)
>     at Parser.write (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Parser.js:43:10)
>     at Protocol.write (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:38:16)
>     at Socket.<anonymous> (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:88:28)
>     at Socket.<anonymous> (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:526:10)
>     at Socket.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Socket.Readable.push (internal/streams/readable.js:223:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
>     --------------------
>     at Protocol._enqueue (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\protocol\Protocol.js:144:48)
>     at Connection.query (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\mysql\lib\Connection.js:198:25)
>     at C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\giveawayfunction.js:56:21
>     at new Promise (<anonymous>)
>     at GiveawayManagerWithOwnDatabase.saveGiveaway (C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\giveawayfunction.js:55:20)
>     at C:\Users\Chatp\OneDrive\Escritorio\Greenshield\Bot\node_modules\discord-giveaways\src\Manager.js:205:24
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**CODE:**

**```
async editGiveaway(messageID, giveawayData){
            return new Promise(function (resolve, reject) {
                sql.query('UPDATE `giveaways` SET `data` = ? WHERE `message_id` = ?', [JSON.stringify(giveawayData), messageID], (err, res) => {
                    if (err) {
                        console.error(err);
                        return reject(err);
                    }
                    resolve(true);
                });
            });
        }
```**

**Comment by Nico105** [comment]
Do you already have `charset: 'utf8mb4'` in your connection config?

**Comment by Chiquis2005** [comment]
![image](https://user-images.githubusercontent.com/44950448/110155980-09f79700-7dac-11eb-87c8-a0319dee3d24.png)

**Comment by Nico105** [comment]
Did this error happen only for this giveaway or does it happen for all?

**Comment by Chiquis2005** [comment]
only happens to me in the giveaway save

**Comment by Nico105** [comment]
could you send your `.start(channel, {})` function object

**Comment by Chiquis2005** [comment]
client.sorteo.start(message.channel, {
        time: ms(args[0]),
        prize: args.slice(2).join(' '),
        winnerCount: parseInt(args[1]),
        messages: {
            giveaway: '\🎉\🎉 \*\*SORTEO\*\* \🎉\🎉',
            giveawayEnded: '\🎉\🎉 \*\*SORTEO TERMINADO\*\* \🎉\🎉',
            timeRemaining: 'Tiempo Restante: \*\*{duration}\*\*!',
            inviteToParticipate: 'Reacciona \🎉 para participar!',
            winMessage: 'Felicidades, {winners}! Acabas de ganar \*\*{prize}\*\*!:partying_face::partying_face:\n{messageURL}',
            embedFooter: 'Sorteo',
            noWinner: 'Sorteo Cancelado, No hay suficientes participantes.',
            hostedBy: 'Hosteado por: {user}',
            winners: 'Ganador(es)',
            endedAt: 'Termina en',
            units: {
                seconds: 'segundos',
                minutes: 'minutos',
                hours: 'horas',
                days: 'dias',
                pluralS: false // Not needed, because units end with a S so it will automatically removed if the unit value is lower than 2
            }
        }
    }).then((gData) => {
        console.log(gData)
    })

**Comment by Nico105** [comment]
works fine for me, do you maybe have some other custom mysql options?

**Comment by Chiquis2005** [comment]
I have everything by default

**Comment by Chiquis2005** [comment]
i did the steps you put in your nmp guide

**Comment by Chiquis2005** [comment]
so? @Nico105

**Comment by Nico105** [comment]
I don't really know... does it happen when it uses the default messages? = comment your custom ones out.

**Comment by Chiquis2005** [comment]
also happens with default messages

**Comment by Chiquis2005** [comment]
and?

**Comment by Nico105** [comment]
What's your mysql server version?

**Comment by Chiquis2005** [comment]
Versión del servidor: 10.5.4-MariaDB-1:10.5.4+maria~bionic - mariadb.org binary distribution

**Comment by Nico105** [comment]
That could explain it, because mariaDB does not have to behave like mysql even though the npm wrapper works mostly with it.

I guess you have to play around with the `JSON.stringify()` else in order to fix it.

Or what you also could try is instead of mysql you install mysql2 (npm) and change `const giveaways = res.map((row) => JSON.parse(row.data));` to `const giveaways = res.map((row) => row.data);`
