### ISSUE TITLE
help guys

### ISSUE THREAD

**Issue by Aditya-coder379** [Androz2091/discord-giveaways#355]
i tried to host it on heroku but when I type node index.js then it throws a error

Error: Cannot find module 'mongoose'
2021-08-13T02:56:40.394255+00:00 app[Worker.1]: Require stack:
2021-08-13T02:56:40.394255+00:00 app[Worker.1]: - /app/index.js
2021-08-13T02:56:40.394256+00:00 app[Worker.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
2021-08-13T02:56:40.394256+00:00 app[Worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:745:27)
2021-08-13T02:56:40.394256+00:00 app[Worker.1]: at Module.require (internal/modules/cjs/loader.js:961:19)
2021-08-13T02:56:40.394257+00:00 app[Worker.1]: at require (internal/modules/cjs/helpers.js:92:18)
2021-08-13T02:56:40.394257+00:00 app[Worker.1]: at Object. (/app/index.js:10:18)
2021-08-13T02:56:40.394257+00:00 app[Worker.1]: at Module._compile (internal/modules/cjs/loader.js:1072:14)
2021-08-13T02:56:40.394257+00:00 app[Worker.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
2021-08-13T02:56:40.394258+00:00 app[Worker.1]: at Module.load (internal/modules/cjs/loader.js:937:32)
2021-08-13T02:56:40.394258+00:00 app[Worker.1]: at Function.Module._load (internal/modules/cjs/loader.js:778:12)
2021-08-13T02:56:40.394258+00:00 app[Worker.1]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
2021-08-13T02:56:40.394259+00:00 app[Worker.1]: code: 'MODULE_NOT_FOUND',
2021-08-13T02:56:40.394259+00:00 app[Worker.1]: requireStack: [ '/app/index.js' ]

but I installed mongoose but idk why it shows this error on heroku
and I also have package.json

**Comment by Nico105** [comment]
bro why tf do you open the same issues over and over again?
