### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'giveaway')

### ISSUE THREAD

**Issue by realpukhraj** [Androz2091/discord-giveaways#500]
```js
TypeError: Cannot read properties of undefined (reading 'giveaway')
0|Realbot  |     at /home/ubuntu/r/node_modules/discord-giveaways/src/Manager.js:604:74
0|Realbot  |     at Array.forEach (<anonymous>)
0|Realbot  |     at GiveawayManagerWithOwnDatabase._checkGiveaway (/home/ubuntu/r/node_modules/discord-giveaways/src/Manager.js:505:24)
0|Realbot  |     at Timeout._onTimeout (/home/ubuntu/r/node_modules/discord-giveaways/src/Manager.js:688:58)
0|Realbot  |     at listOnTimeout (node:internal/timers:559:17)
0|Realbot  |     at processTimers (node:internal/timers:502:7)
0|Realbot  |  [Error_Handling] :: Unhandled Rejection/Catch
```

**Comment by mooyg** [comment]
Where is this coming from? can you show your code
