### ISSUE TITLE
no winners 

### ISSUE THREAD

**Issue by 3061LRTAGSPKJMORMRT** [Androz2091/discord-giveaways#82]
Bot always says no winners even if I deleted the exemptPermissions. I'm on v4. 2.1 and on djs v11. 6.4

**Comment by Androz2091** [comment]
Hello,
Could you send your code please? (where you create the GiveawaysManager instance and where you start the giveaway)

**Comment by 3061LRTAGSPKJMORMRT** [comment]
So the below is my index.js

`const db = require("quick.db");
const Discord = require("discord.js");
/*let prefix = db.get(`prefix_${message.guild.id}`);
if (!prefix) {
  db.set(`prefix_${message.guild.id}`, "+");
  prefix = db.get(`prefix_${message.guild.id}`);
}*/

const fs = require("fs"),
  client = new Discord.Client(),
  settings = {
    token: process.env.TOKEN
  };
if (!db.get("giveaways")) db.set("giveaways", []);
const { GiveawaysManager } = require("discord-giveaways");
const GiveawayManagerWithOwnDatabase = class extends GiveawaysManager {
  // This function is called when the manager needs to get all the giveaway stored in the database.
  async getAllGiveaways() {
    // Get all the giveaway in the database
    return db.get("giveaways");
  }

  // This function is called when a giveaway needs to be saved in the database (when a giveaway is created or when a giveaway is edited).
  async saveGiveaway(messageID, giveawayData) {
    // Add the new one
    db.push("giveaways", giveawayData);
    // Don't forget to return something!
    return true;
  }

  async editGiveaway(messageID, giveawayData) {
    // Gets all the current giveaways
    const giveaways = db.get("giveaways");
    // Remove the old giveaway from the current giveaways ID
    const newGiveawaysArray = giveaways.filter(
      giveaway => giveaway.messageID !== messageID
    );
    // Push the new giveaway to the array
    newGiveawaysArray.push(giveawayData);
    // Save the updated array
    db.set("giveaways", newGiveawaysArray);
    // Don't forget to return something!
    return true;
  }

  // This function is called when a giveaway needs to be deleted from the database.
  async deleteGiveaway(messageID) {
    // Remove the giveaway from the array
    const newGiveawaysArray = db
      .get("giveaways")
      .filter(giveaway => giveaway.messageID !== messageID);
    // Save the updated array
    db.set("giveaways", newGiveawaysArray);
    // Don't forget to return something!
    return true;
  }
};

// Create a new instance of your new class
const manager = new GiveawayManagerWithOwnDatabase(client, {
  storage: false, // Important - use false instead of a storage path
  updateCountdownEvery: 10000,
  default: {
    botsCanWin: false,
    embedColor: "#FF0000",
    reaction: "579011246024556546"
  }
});
// We now have a giveawaysManager property to access the manager everywhere!
client.giveawaysManager = manager;

//const client = new Discord.Client();
client.commands = new Discord.Collection();

const cooldowns = new Discord.Collection();

const commandFiles = fs
  .readdirSync("./commands")
  .filter(file => file.endsWith(".js"));

for (const file of commandFiles) {
  const command = require(`./commands/${file}`);
  client.commands.set(command.name, command);
}

client.on("ready", () => {
  console.log("Ready!");
  client.user.setActivity(`version 0.3.21`, { type: "PLAYING" });
});

//client.on("debug", console.log)
let prefix = '+' 
client.on("message", message => {
  if (message.channel.type != "dm") {
    prefix = db.get(`prefix_${message.guild.id}`);
    if (!prefix) {
      db.set(`prefix_${message.guild.id}`, "+");
      prefix = db.get(`prefix_${message.guild.id}`);
    }
    if (message.content == "<@578945590210068490>")
      return message.channel.send(
        "I think you are lost. My prefix for this server is `" + prefix + "`!"
      );
  }
  /*if (message.content.includes('fuck')) {
    message.delete() 
    let umkk = 'boomerblindshish' 
    message.channel.send(`${message.author} said ${umkk} is a manager that doesnt know how to countdown.`) //STOP IT KACHIKAWAWA NO U
    } */
  /*  if (
    message.guild.id != "584044607910969386" &&
    message.guild.id != "565880459788025876"
  )
    return;*/
  // Game Chat
  if (message.channel.type == "dm" && !message.author.bot) {
    if (!message.content.startsWith("+")) {
      let chatDisabled = db.get("chatDisabled");
      if (chatDisabled === true) {
        message.author.send("You can't send messages right now!");
      } else {
        let players = db.get("players");
        let ap = db.get("playerNumb");
        if (players.includes(message.author.username)) {
          if (message.content.includes("\n")) {
            message.author.send("Your message contains more than one line!");
          } else {
            let discussion = db.get("discussion");
            if (discussion != true) return;
            for (let i = 1; i <= ap; i++) {
              let player = db.get(`player_${i}`);
              let guy = client.users.get(player);
              if (player != message.author.id) {
                guy.send(message.author.username + ": " + message.content);
              }
            }
          }
        }
      }
    }
  }
  /*if (message.content.startsWith('i\'m') || message.content.startsWith('im') || message.content.startsWith('I\'m') || message.content.startsWith('Im')) {
    const arg = message.content.slice(2).split(/ +/);
    message.channel.send(`Hi ${arg}, I'm dad`)
  }*/
  if (!message.content.startsWith(prefix) || message.author.bot) return;
  let code;

  var alivePlayer = 0;
  const args = message.content.slice(prefix.length).split(/ +/);
  const commandName = args.shift().toLowerCase();
  console.log(commandName);
  //if (!client.commands.has(commandName)) return;

  const command =
    client.commands.get(commandName) ||
    client.commands.find(
      cmd => cmd.aliases && cmd.aliases.includes(commandName)
    );
  if (!command) return;
  if (!cooldowns.has(command.name)) {
    cooldowns.set(command.name, new Discord.Collection());
  }

  try {
    command.run(message, args, client, code);
  } catch (error) {
    console.error(error);
    message.channel.send(
      "Uhh, there was an error when executing the command! This has been reported to the Dev! We are sorry for the inconvenience caused!"
    );
    client.channels
      .get("682915030437724194")
      .send("There had been an error! The command needs fixing!");
    console.log(command);
  }
});
let token = process.env.TOKEN;
client.login(token).then(() => console.log(client.guilds.size));

// server.js
// where your node app starts

// we've started you off with Express (https://expressjs.com/)
// but feel free to use whatever libraries or frameworks you'd like through `package.json`.
const express = require("express");
const app = express();

// our default array of dreams
const dreams = [
  "Find and count some sheep",
  "Climb a really tall mountain",
  "Wash the dishes"
];

// make all the files in 'public' available
// https://expressjs.com/en/starter/static-files.html
app.use(express.static("public"));

// https://expressjs.com/en/starter/basic-routing.html
app.get("/", (request, response) => {
  response.sendFile(__dirname + "/views/index.html");
});

// send the default array of dreams to the webpage
app.get("/dreams", (request, response) => {
  // express helps us take JS objects and send them as JSON
  response.json(dreams);
});

// listen for requests :)
const listener = app.listen(process.env.PORT, () => {
  console.log("Your app is listening on port " + listener.address().port);
});

// =======================================================================
var server = require("http").createServer(app);
var io = require("socket.io")(server);
var port = process.env.PORT || 3000;

// Routing
app.use(express.static("public"));
var numUsers = 0;

io.on("connection", function(socket) {
  var addedUser = false;

  // when the client emits 'new message', this listens and executes
  socket.on("new message", function(data) {
    // we tell the client to execute 'new message'
    socket.broadcast.emit("new message", {
      username: socket.username,
      message: data
    });
  });

  // when the client emits 'add user', this listens and executes
  socket.on("add user", function(username) {
    if (addedUser) return;

    // we store the username in the socket session for this client
    socket.username = username;
    ++numUsers;
    addedUser = true;
    socket.emit("login", {
      numUsers: numUsers
    });
    // echo globally (all clients) that a person has connected
    socket.broadcast.emit("user joined", {
      username: socket.username,
      numUsers: numUsers
    });
  });

  // when the client emits 'typing', we broadcast it to others
  socket.on("typing", function() {
    socket.broadcast.emit("typing", {
      username: socket.username
    });
  });

  // when the client emits 'stop typing', we broadcast it to others
  socket.on("stop typing", function() {
    socket.broadcast.emit("stop typing", {
      username: socket.username
    });
  });

  // when the user disconnects.. perform this
  socket.on("disconnect", function() {
    if (addedUser) {
      --numUsers;

      // echo globally that this client has left
      socket.broadcast.emit("user left", {
        username: socket.username,
        numUsers: numUsers
      });
    }
  });
});

// node server.js
`

this is my start giveaway command 

`javascript
const Discord = require("discord.js");
const db = require("quick.db");
const ms = require("ms");

module.exports = {
  name: "gstart",
  run: async (message, args, client) => {
    let c = message.mentions.channels.first() || message.channel;
    let role = await db.fetch(`gwarole_${message.guild.id}`);
    if (role == null)
      return await message.channel.send(
        "No role found to ping! Please set a role by doing `+grole <role-id>`!"
      );
    role = message.guild.roles.find(r => r.id === role)
    client.giveawaysManager.start(c, {
      time: ms(args[0]),
      prize: args.slice(2).join(" "),
      winnerCount: parseInt(args[1]),
      messages: {
        giveaway: role + "\n\n🎉🎉 **GIVEAWAY** 🎉🎉",
        giveawayEnded: role + "\n\n🎉🎉 **GIVEAWAY ENDED** 🎉🎉",
        timeRemaining: "Time remaining: **{duration}**!",
        inviteToParticipate: "React with <:cultist:579011246024556546> to participate!",
        winMessage: "Congratulations, {winners}! You won **{prize}**!",
        embedFooter: "Giveaways",
        noWinner:
          "<:not_available:689083576498913283> I could not decide a winner to choose!",
        hostedBy: "Hosted by: {user}",
        winners: "winner(s)",
        endedAt: "Ended at",
        units: {
          seconds: "seconds",
          minutes: "minutes",
          hours: "hours",
          days: "days"
        }
      }
    });
  }
};
 `

**Comment by 3061LRTAGSPKJMORMRT** [comment]
so are you gonna reply or not?

**Comment by Xynnix** [comment]
Maybe I am entirely incorrect and such but if you read this modules `package.json` it has discord.js v12.2.0 as a requirement. I would recommend updating your bots code to use v12.2.0 anyways even if I'm by chance incorrect since it will need it anyways as the possibility of Discord.js v11 becoming out of date due to domain changes. Even if not, better safe than sorry. And it may help fix your giveaway issue? 😅 I can be wrong since I'm just basing off the package.json.

**Comment by 3061LRTAGSPKJMORMRT** [comment]
alright. i'll try updating and let you know

**Comment by 3061LRTAGSPKJMORMRT** [comment]
```
(node:704) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
at Object.run (/app/commands/gstart.js:13:29)
```

gets me this error. (this bot is v12)

**Comment by NicoHd105** [comment]
Are you still facing this?
If hopefully not, then please provide the solution/what you did to fix your last error and then close this issue.

**Comment by 3061LRTAGSPKJMORMRT** [comment]
> Are you still facing this?
> If hopefully not, then please provide the solution/what you did to fix your last error and then close this issue.

Yes.... i am still facing this

**Comment by NicoHd105** [comment]
Have you tried updating to the new version?

**Comment by panlazy** [comment]
Hello, right now I've the same issue everything is in latest version code is exactly same with the example I use mongodb. I can successfully start the giveaway. I can see the giveaway details in the db but when someone is react to giveaway emoji they're not saving to db and my guess is this is the reason of there is no winners. Am I missing something?

Happy new year :tada:

**Comment by Nico105** [comment]
> Hello, right now I've the same issue everything is in latest version code is exactly same with the example I use mongodb. I can successfully start the giveaway.
> 
> I can see the giveaway details in the db but when someone is react to giveaway emoji they're not saving to db, even if it shouldn't be saved to db the `winners` array is empty when giveaway's ended. My guess is this is the reason of there is no winners. I can see in the console who is reacted. Am I missing something?
> 
> Happy new year 🎉

Did you make sure that if you have the `exemptPermissions` or `exemptMembers` property in the giveaway object or in the initialization of your giveaway manager, that they are alright?
Does anything change if you use `npm install Androz2091/discord-giveaways#develop`?

**Comment by panlazy** [comment]
> > Hello, right now I've the same issue everything is in latest version code is exactly same with the example I use mongodb. I can successfully start the giveaway.
> > I can see the giveaway details in the db but when someone is react to giveaway emoji they're not saving to db, even if it shouldn't be saved to db the `winners` array is empty when giveaway's ended. My guess is this is the reason of there is no winners. I can see in the console who is reacted. Am I missing something?
> > Happy new year tada
> 
> Did you make sure that if you have the `exemptPermissions` or `exemptMembers` property in the giveaway object or in the initialization of your giveaway manager, that they are alright?
> Does anything change if you use `npm install Androz2091/discord-giveaways#develop`?

Thank you for a quick reply. I'm dumb that was a permission issue. I removed `exemptPermissions` now its working! But i've a another issue tho :laughing: 

```
return new VersionError(doc, version, modifiedPaths);
         ^

VersionError: No matching document found for id "5fede2f679d486beecdbc76f" version 5 modifiedPaths "data"
return new VersionError(doc, version, modifiedPaths);
         ^

VersionError: No matching document found for id "5fede2f679d486beecdbc76f" version 5 modifiedPaths "data"
```
It cannot edit the database, the ID/version is correct. I didn't use quickmongo before so If you have any suggestion I'll be glad!
![db](https://i.imgur.com/Ll5jZ1D.png)

**Comment by Nico105** [comment]
Ahm is that some custom code of yours? 
https://github.com/Androz2091/discord-giveaways/blob/master/examples/custom-databases/mongodb.js is the official quickmongo example for the general functionality of the module, if you have done something custom then idk what is wrong but if you use the example then everything should work fine.

**Comment by panlazy** [comment]
> ```
> (node:704) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'start' of undefined
> at Object.run (/app/commands/gstart.js:13:29)
> ```
> 
> gets me this error. (this bot is v12)

You have to upgrade discord.js. I didn't work me for 12.2.0 make sure you are using 12.5.1. Also make sure to check permissions when initialize giveawayManager.

> Ahm is that some custom code of yours?
> https://github.com/Androz2091/discord-giveaways/blob/master/examples/custom-databases/mongodb.js is the official quickmongo example for the general functionality of the module, if you have done something custom then idk what is wrong but if you use the example then everything should work fine.

Nope, I just copy pasted the class It's exactly same :smile: I'll try to fix it. If it won't works, I might switch to mongoose I can open a pull request for mongoose with example if I switch to it. I doubt it's a issue related to document version.

Thanks a lot!
